version: '3'

services:
  selenium-chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"  # Selenium server
      - "5900:5900"  # VNC port
    environment:
      - VNC_PASSWORD=1234  # Set your desired VNC password here
    networks:
      - selenium

networks:
  selenium:
